# KINEMATICS OF DIFFERENTIAL

### IMPORT LIBRARIES

In [2]:
import numpy as np

The kinematics of a differential robot, often referred to as "Differential Drive Kinematics," is a mathematical framework that describes how the robot moves and changes its position and orientation based on the velocities of its two wheels. Differential drive robots are characterized by having two independently controllable wheels, typically placed on a common axis, and a caster wheel or other passive support. These robots are commonly used in various applications, including mobile robots, robotic platforms, and even some types of robotic vehicles.

Here are the key components of the kinematics of a differential robot:

1. **Wheel Velocities (Vl and Vr)**:
   - Vl represents the linear velocity of the left wheel.
   - Vr represents the linear velocity of the right wheel.

2. **Robot's Linear Velocity (V)**:
   - The robot's linear velocity, V, is the average of the linear velocities of the left and right wheels:
     V = (Vl + Vr) / 2

3. **Robot's Angular Velocity (ω)**:
   - The robot's angular velocity, ω, is determined by the difference in linear velocities of the left and right wheels, divided by the distance between the wheels (the robot's wheelbase):
     ω = (Vr - Vl) / W
     where W is the wheelbase, the distance between the two wheels.

4. **Robot's Position and Orientation (x, y, θ)**:
   - The robot's position (x, y) in a global coordinate system is determined by integrating its linear velocity over time. The orientation (θ) is determined by integrating its angular velocity.
     - x(t+Δt) = x(t) + V * cos(θ) * Δt
     - y(t+Δt) = y(t) + V * sin(θ) * Δt
     - θ(t+Δt) = θ(t) + ω * Δt

These equations allow you to compute how a differential drive robot's position and orientation change as it moves with specified wheel velocities. They form the basis for controlling and navigating such robots, including tasks like path following, obstacle avoidance, and mapping.

Understanding the kinematics of a differential robot is crucial for developing control algorithms and planning its movements effectively in different environments.

## 1- FORWARD KINEMATICS

##### 1.1- Local Frame

<center>
<img src="assets/imgs/two_diff_robot.jpg" width=900 height=600 />
</center>

<center>
<img src="assets/imgs/two_kinematics_schame.png" width=900 height=600 />
</center>

* Assume Angular velocit of Wheels:
    * wr : angular velocity of Right wheel
    * wl : angular velocity of Left wheel

<center>
<img src="assets/imgs/local_diff.png" width=300 height=300 />
</center>

In [3]:
# Constants
r  = 0.1 # meter
b  = 0.2 # meter

# Variables
wr = 10       # rad/sec
wl = 0      # rad/sec


vr = wr * r   # linear velocity of right wheel
vl = wl * r   # linear velocity of right wheel


# Excuse Kinematics
Vx = (1/2)  * vr  + (1/2) *  vl
Vy = (0  )  * vr  + (0  ) *  vl
w  = (1/b)  * vr  - (1/b) *  vl

print(f"Vx : {Vx}")
print(f"Vy : {Vy}")
print(f"w  : {w}")

Vx : 0.5
Vy : 0.0
w  : 5.0


***

##### 1.1- Global Frame

<center>
<img src="assets/imgs/local_to_global.png" width=600 height=600 />
</center>

<center>
<img src="assets/imgs/global_equs.png" width=300 height=200 />
</center>

In [4]:
# Constants
r  = 0.1 # meter
b  = 0.2 # meter

# Variables
wr = 10       # rad/sec
wl = -10       # rad/sec


vr = wr * r   # linear velocity of right wheel
vl = wl * r   # linear velocity of right wheel

theta = 180

# Excuse local Kinematics
Vx = (1/2)  * vr  + (1/2) *  vl
Vy = (0  )  * vr  + (0  ) *  vl
w  = (1/b)  * vr  - (1/b) *  vl

Vgx= Vx * np.cos( theta * (np.pi/180) )
Vgy= Vx * np.sin( theta * (np.pi/180) )
Wg = w

if np.abs(Vgx) < 1e-5 : Vgx = 0
if np.abs(Vgy) < 1e-5 : Vgy = 0
if np.abs(Wg ) < 1e-5 : Wg = 0

print(f"Vgx : {Vgx}")
print(f"Vgy : {Vgy}")
print(f"Wg  : {Wg}")

Vgx : 0
Vgy : 0
Wg  : 10.0


***

### 1.3- Matrix Form

<center>
<img src="assets/imgs/matrix_diff.png" width=300 height=200 />
</center>

In [9]:
# Constants
r  = 0.1 # meter
b  = 0.2 # meter

# Variables
wr = 10       # rad/sec
wl = 10       # rad/sec

vr = wr * r   # linear velocity of right wheel
vl = wl * r   # linear velocity of right wheel


# input
W = np.array([ [wl], [wr] ])

Kinematics = np.array([ [r/2, r/2], [0, 0] ,[-r/b, r/b]])


# Output
Vl = Kinematics @ W

print(np.round(Vl,2))

[[1.]
 [0.]
 [0.]]


<center>
<img src="assets/imgs/rot_mat.png" width=300 height=200 />
</center>

In [12]:
theta = 45

Rot  = np.array([ [np.cos(theta * (np.pi/180)) , -np.sin(theta * (np.pi/180)), 0 ], 
                  [np.sin(theta * (np.pi/180)) , np.cos(theta * (np.pi/180)) , 0 ],
                  [             0              ,              0              , 1 ]])

# Output
Vg = Rot  @  Vl 



print(f"Vl : \n{np.round(Vl,2)}")
print(f"\nVg: \n{np.round(Vg,2)}")

Vl : 
[[1.]
 [0.]
 [0.]]

Vg: 
[[0.71]
 [0.71]
 [0.  ]]


***

### 1.4- Inverse Kinematics

In [13]:
np.linalg.pinv(Kinematics)

array([[10.,  0., -1.],
       [10.,  0.,  1.]])

In [16]:
# Constants
r  = 0.1 # meter
b  = 0.2 # meter

# Variables
vx = 10       # m/sec
vy = 0       # m/sec
w  = 10     


# input
V = np.array([ [vx], [vy], [w] ])

Kinematics = np.array([ [r/2, r/2], [0, 0] ,[-r/b, r/b]])


# Output
W = np.linalg.pinv(Kinematics) @ V

print(W)

[[ 90.]
 [110.]]


array([[10.,  0., -1.],
       [10.,  0.,  1.]])